# Generated by Django 5.2 on 2025-04-15 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon_web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('specialization', models.CharField(max_length=100)),
            ],
        ),
    ]
