# Generated by Django 5.2 on 2025-04-18 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon_web', '0002_master'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='customer',
            name='referral_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='referred_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='salon_web.customer'),
        ),
        migrations.AddField(
            model_name='service',
            name='premium_price',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=50),
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.DecimalField(decimal_places=3, max_digits=50),
        ),
    ]
