# Generated by Django 5.2 on 2025-04-18 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon_web', '0003_customer_discount_customer_referral_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='final_price',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=50, null=True),
        ),
    ]
