# Generated by Django 5.2 on 2025-05-14 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salon_web', '0011_alter_employee_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='user',
        ),
    ]
