# Generated by Django 5.2 on 2025-05-17 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon_web', '0012_remove_employee_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='discount_applied',
            field=models.CharField(choices=[("yo'q", "yo'q"), ('ha', 'ha')], default="yo'q", max_length=5),
        ),
        migrations.AddField(
            model_name='booking',
            name='price_type',
            field=models.CharField(choices=[('Oddiy', 'Oddiy'), ('Premium', 'Premium'), ('Boshqa', 'Boshqa')], default='Oddiy', max_length=20),
        ),
    ]
